TEMPLATE = app
DESTDIR = dist/Release/GNU-Linux-x86
TARGET = kajammer
VERSION = 1.0.0
CONFIG -= debug_and_release
CONFIG += release 
QT = core gui phonon
SOURCES += mainwindow.cpp mediacontrols.cpp menubar.cpp main.cpp
HEADERS += menubar.h mainwindow.h mediacontrols.h
FORMS +=
RESOURCES +=
TRANSLATIONS +=
OBJECTS_DIR = build/Release/GNU-Linux-x86
MOC_DIR = 
RCC_DIR = 
UI_DIR = 
QMAKE_CC = gcc
QMAKE_CXX = g++
DEFINES += 
INCLUDEPATH += 
LIBS += 
